<base target="_blank">
<h2>About This Gallery</h2><br>

<center><font face="Arial"><b>Background Code:</b><br>Thumbnail creation powered by <a href="http://jack-the-ripper.mine.nu/justThumb/">justThumb</a> found at <a href="http://www.php.net/manual/en/ref.image.php">http://www.php.net/manual/en/ref.image.php</a><br><br>

Main gallery area coded primarily by me, Adam (ahwm on SDS Forum), with lots of help from Wayne (Dmb1981 on SDS Forum).<br><br>

To see more of our work, visit our website at <a href="http://www.thescripters.com">TheScripters.com</a>...<br><br>

<a href="caps" target="_self"><font size="+1">Home</font></a></font></center>
