<hr><br>
 <a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.kpfanworld.com" target="_blank">
  <img style="border:0;width:88px;height:31px"
       src="http://jigsaw.w3.org/css-validator/images/vcss" 
       alt="Valid CSS!"></a>&nbsp;&nbsp;
    <a href="http://validator.w3.org/check?uri=http://www.kpfanworld.com" target="_blank"><img
        src="http://www.w3.org/Icons/valid-html401"
        alt="Valid HTML 4.01 Transitional" border="0" height="31" width="88"></a>&nbsp;&nbsp;<a href="http://www.php.net" target="_blank"><img src="images/php-power-black.gif" alt="Powered by PHP" border="0"></a>&nbsp;&nbsp;<a href="http://www.oneshare.com?kbid=2220&amp;sub=kpfw&amp;img=osos88x31.gif"><img src="http://oneshare.org/images/myap/osos88x31.gif" alt="OneShare.com"border="0"></a>
<img src="http://www.oneshareaffiliates.com/showban.asp?id=2220&amp;sub=kpfw&amp;img=osos88x31.gif" border="0" alt="">&nbsp;&nbsp;<?php include "banner/ipw.php"; ?>&nbsp;&nbsp;<?php include "banner/bh.php"; ?>&nbsp;&nbsp;<a href="http://www.thescripters.com" target="_blank"><img src="http://www.thescripters.com/ts-coded2.png" width="102" height="32" alt="Coded by TheScripters.com" border="0"></a><br>
<script type="text/javascript"><!--
google_ad_client = "pub-8764799239146712";
google_alternate_ad_url = "http://www.thescripters.com/extra/234_60.php";
google_ad_width = 234;
google_ad_height = 60;
google_ad_format = "234x60_as";
google_ad_type = "text";
google_ad_channel = "";
google_color_border = "FFFFFF";
google_color_bg = "000000";
google_color_link = "FFFF00";
google_color_text = "FFFFFF";
google_color_url = "00FF00";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script></center>
<h6>&copy; 2006-2009 <a href="http://www.kpfanworld.com">Kim Possible Fan World</a>; All rights reserved<br>Design by <a href="http://www.thescripters.com" target="_blank">TheScripters.com</a><br>"Kim Possible" &copy; 2002-2007 <a href="http://www.disney.com" target="_blank">Disney</a><br>KP Fan World is in no way affiliated with the Disney Company</h6>
<!-- Start of StatCounter Code -->
<script type="text/javascript">
var sc_project=2851455; 
var sc_invisible=0; 
var sc_partition=29; 
var sc_security="204d6af8"; 
</script>

<script type="text/javascript" src="http://www.statcounter.com/counter/counter_xhtml.js"></script><noscript><div class="statcounter"><a class="statcounter" href="http://www.statcounter.com/"><img class="statcounter" src="http://c30.statcounter.com/2851455/0/204d6af8/0/" alt="website page counter" /></a></div></noscript>
<!-- End of StatCounter Code -->
</body>
</html>
