<br>
<center><font face="Arial" size="2">This is a page for screencaps of <i>Kim Possible: So The Drama</i>. I had a few friends who love looking at screencaps. And a few others who needed hi-res (high resolution) for other projects. Here I've created and compiled many many many screencaps from the movie. There is really only one easy way to view them. But I'll include an index/table of contents for each section when they're done.<br><br>

For more information on this gallery, click <a href="about.php">here</a>.<br><br>

So without further delay, I present you <i>So The Drama</i>!<br><br>
<table><tr><td>
<ul>
<li><a href="index.php?pic=1">Beginning/Opening Sequence</a> <b>1-420</b></li>
<li><a href="index.php?pic=421">Opening Credits Sequence</a> <b>421-500</b></li>
<li><a href="index.php?pic=501">Trip Home</a> <b>501-640</b></li>
<li><a href="index.php?pic=641">Drakken's Lair</a> <b>641-724</b></li>
<li><a href="index.php?pic=725">Start of gym scene</a> <b>725-751</b></li>
<li><a href="index.php?pic=752">Start Bueno Nacho</a> <b>752-775</b></li>
<li><a href="index.php?pic=776">Start Bermuda Triangle</a> <b>776-1140</b></li>
<ul><li><a href="index.php?pic=781">Kim/Ron on boat with Mr. Bailey</a> - 781-787</li>
<li><a href="index.php?pic=788">Drakken/Shego Main entrance</a> - 788-794</li>
<li><a href="index.php?pic=795">Start Underwater sequence</a> - 795-870</li>
<li><a href="index.php?pic=871">Start Drakken/Big Daddy Brotherson</a> - 871-886</li>
<li><a href="index.php?pic=887">Start Kim/Ron infiltration</a> - 887-908</li>
<li><a href="index.php?pic=909">Start Ron/Poker</a> - 909-914</li>
<li><a href="index.php?pic=915">Continue Drakken/Big Daddy Brotherson</a> - 915-923</li>
<li><a href="index.php?pic=924">Start Kim/Shego Fight</a> - 924-991</li>
<li><a href="index.php?pic=992">Continue Ron/Poker</a> - 992-1022</li>
<li><a href="index.php?pic=1023">Continue Kim/Shego Fight</a> - 1023-1054</li>
<li><a href="index.php?pic=1055">Continue Drakken/Big Daddy Brotherson</a> - 1055-1067</li>
<li><a href="index.php?pic=1067">Continue Kim/Shego Fight</a> - 1067-1140</li>
</ul>
<li><a href="index.php?pic=1141">Start School Scene</a> <b>1141-1176</b></li>
<li><a href="index.php?pic=1177">Start Home/Prom Discussion</a> <b>1177-1203</b></li>
<li><a href="index.php?pic=1204">Start School/Erik</a> <b>1204-1300</b></li>
<li><a href="index.php?pic=1301">Start Science Center/Pizza Night</a> <b>1301-1355</b></li>
<li><a href="index.php?pic=1356">Start Bueno Nacho/Ned/Lars</a> <b>1356-1370</b></li>
<li><a href="index.php?pic=1371">Begin Dad Rescue</a> <b>1371-1462</b></li>
<li><a href="index.php?pic=1463">Club Banana</a> <b>1463-1508</b></li>
<li><a href="index.php?pic=1509">Shego/Drakken's Plan</a> <b>1509-1528</b></li>
<li><a href="index.php?pic=1529">Begin Li'l Diablos/Bueno Nacho</a> <b>1529-1555</b></li>
<li><a href="index.php?pic=1556">Begin Kim/Ron Treehouse</a> <b>1556-1606</b></li>
<li><a href="index.php?pic=1607">Erik/Kim Walk Home</a> <b>1607-1613</b></li>
<li><a href="index.php?pic=1614">Ron Prom Preparation</a> <b>1614-1633</b></li>
<li><a href="index.php?pic=1634">Erik/Kim Possible Residence Before Prom</a> <b>1634-1671</b></li>
<li><a href="index.php?pic=1672">Prom/Bueno Nacho</a> <b>1672~1700</b> - <i>INCOMPLETE</i></li>
<ul><li><a href="index.php?pic=1672">Erik/Kim Dancing</a> - 1672-1685</li>
<li><a href="index.php?pic=1686">Ron at Bueno Nacho</a> - 1686-1740</li>
<li><a href="index.php?pic=1741">L'il Diablos</a> - 1741-1756</li>
<li><a href="index.php?pic=1757">Continue Prom w/ Kim/Erik</a> - 1757-1763</li>
<li><a href="index.php?pic=1764">Continue L'il Diablos/Ron</a> - 1764-1792</li>
<li><a href="index.php?pic=1793">COntinue Prom Discussion</a> - 1793~1800 - <i>INCOMPLETE</i></li></ul>
</ul></td></tr></table>

<font size="3">Thumbnails: <a href="thumb.php?start=1">1-100</a> || <a href="thumb.php?start=101">101-200</a> || <a href="thumb.php?start=201">201-300</a> || <a href="thumb.php?start=301">301-400</a> || <a href="thumb.php?start=401">401-500</a> || <a href="thumb.php?start=501">501-600</a> || <a href="thumb.php?start=601">601-700</a> || <a href="thumb.php?start=701">701-800</a> || <a href="thumb.php?start=801">801-900</a> || <a href="thumb.php?start=901">901-1000</a> || <a href="thumb.php?start=1001">1001-1100</a> || <a href="thumb.php?start=1101">1101-1200</a> || <a href="thumb.php?start=1201">1201-1300</a> || <a href="thumb.php?start=1301">1301-1400</a> || <a href="thumb.php?start=1401">1401-1500</a> || <a href="thumb.php?start=1501">1501-1600</a> || <a href="thumb.php?start=1601">1601-1700</a> || <a href="thumb.php?start=1701">1701-1800</a></font><br>Please allow time to load. Even on high speed connection, it may take anywhere from 10-30 seconds for all images to load.<br><br><br>

<i><font size="+1">Images best viewed at 1024x768 screen resolution or higher</font></i><br><br>

<table><tr><td><font size="2">Gallery Stats:<br>
Image Resolution: 1015x570 pixels High Quality JPEG, average 230-250 KB each.<br>
Number of images in Gallery: <b>1800</b><br>Overall usage: <b>438 MB</b></font></td></tr></table>
<A HREF="http://www.digits.com/" target="_blank"><IMG SRC="http://counter.digits.com/wc/-d/4/stdcaps" ALIGN=middle title="WebCounter" WIDTH=60 HEIGHT=20 BORDER=0></a></font></center>
