<!-- includes/pm_header.inc -->
<table align="center" width="75%" border="1" rules="none">
  <tr>
    <td><a href="pmaction.php?mode=compose"><img src="images/send_pm.jpg" border="0"></a></td>
  </tr>
  <tr>
    <th>Private Messages</th>
  </tr>
  <tr>
    <td><table width="100%">
      <tr>
        <th class="heading"></th>
        <th class="heading">Subject</th>
        <th class="heading">From</th>
        <th class="heading">Date Sent</th>
      </tr>
