<hr><div style="width:100%;text-align:right;height:15px"><a href="rss.php"><img src="rss.gif" border="0" alt="RSS"><img src="xml.gif" border="0" alt="XML"></a></div>
 <a href="http://jigsaw.w3.org/css-validator/validator?uri=http://www.kpfanfiction.com" target="_blank">
  <img style="border:0;width:88px;height:31px"
       src="http://jigsaw.w3.org/css-validator/images/vcss" 
       alt="Valid CSS!"></a>&nbsp;&nbsp;
    <a href="http://validator.w3.org/check?uri=http://www.kpfanfiction.com" target="_blank"><img
        src="http://www.w3.org/Icons/valid-html401"
        alt="Valid HTML 4.01 Transitional" border="0" height="31" width="88"></a>&nbsp;&nbsp;<a href="http://www.php.net" target="_blank"><img src="images/php-power-black.gif" alt="Powered by PHP" border="0"></a>&nbsp;&nbsp;<a href="http://www.thescripters.com" target="_blank"><img src="http://www.thescripters.com/ts-coded2.png" width="102" height="32" alt="Coded by TheScripters.com" border="0"></a><br>
<script type="text/javascript"><!--
google_ad_client = "pub-8764799239146712";
google_ad_width = 468;
google_ad_height = 15;
google_ad_format = "468x15_0ads_al";
google_ad_channel ="";
google_color_border = "FFFFFF";
google_color_bg = "000000";
google_color_link = "FFFF00";
google_color_text = "FFFFFF";
google_color_url = "FFFF00";
//--></script>
<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script></center>
<h6>&copy; 2006-2007 <a href="http://www.kpfanworld.com">Kim Possible Fan World</a>; All rights reserved<br>"Kim Possible" &copy; 2002-2006 <a href="http://www.disney.com" target="_blank">Disney</a><br>KP Fan World is in no way affiliated with the Disney Company</h6>
</body>
</html>
