<center><u><font size="4"><b><i>______________________________________________________________________________________</i></b></font></u><br />
<font size="1">PHP Scripts coded and © 2006-2007 to <a href="mailto:caps@kpfanworld.com?subject=Kim Possible Screen Caps">Brian Wallace</a> All Rights Reserved<br />
&quot;Kim Possible&quot; © 2002-2007 <a target="_blank" href="http://www.disney.com">Disney</a><br />
This site is in no way affiliated with the Disney Company<br />Hosted by <a href="http://bluehost.com">Blue Host</a></font><br />
    <a href="http://validator.w3.org/check?uri=referer"><img
        src="http://www.w3.org/Icons/valid-xhtml10"
        alt="Valid XHTML 1.0 Transitional" height="31" width="88" border="0" /></a>&nbsp;&nbsp;
    <a href="http://www.php.net" target="_blank"><img src="http://caps.kpfanworld.com/images/php-power-black.gif" alt="Powered by PHP" border="0" /></a>&nbsp;&nbsp;
    <script type="text/javascript" src="http://www.bluehost.com/src/js/thescripters/kpfwfooter/88x31/5.gif"></script>
<!-- Start of StatCounter Code -->
<a href="http://www.statcounter.com/" target="_blank"><img src="http://c25.statcounter.com/counter.php?sc_project=2522787&amp;java=0&amp;security=e190742a&amp;invisible=0" alt="free hit counter" border="0" /></a> 
<!-- End of StatCounter Code -->
</center>
</body>
</html>