<h2>Submit Spoilers</h2><br><br>

<center><span class="text">If it is an episode title/description, please include episode number if available.</span><br>
<form action="spoilers?p=submit" method="post">
<span class="formsubmit">Spoiler Text: <input type="text" maxlength="255" name="Spoilertext"><br>
Category: <select name="SpoilerCat"><option name="SpoilerCat" value="Plot">Plot</option><option name="SpoilerCat" value="Episode">Episode Title/Description</option><option name="SpoilerCat" value="Miscellaneous">Miscellaneous</option></select><br><input type="submit" value="Submit"></form></span></center><p>&nbsp;</p>

<center><a href="index.php?show=kp&confirm=true">Back to spoilers</a></center>
